language: clojure
lein: lein
cache:
  directories:
  - "$HOME/.m2"
jdk:
  - oraclejdk8
env:
  global:
script:
  - rm -rf dist || exit 0
  - mkdir dist
  - lein clean
  - lein with-profile prod cljsbuild once ui
