version: 2
jobs:
  build:
    working_directory: /var/cleo-poc
    docker:
      - image: openjdk:8
    environment:
      LEIN_ROOT=nbd
    steps:
      - checkout
      - restore_cache:
          keys:
            - << checksum "project.clj" >>
            - cljs
      - run: bin/lein deps
      - run: bin/lein with-profile prod cljsbuild once ui
      - save_cache:
          paths:
            - ~/target
            - ~/.m2
            - ~/.lein
          key: cljs
      - save_cache:
          paths:
            - $HOME/.m2
            - $HOME/.lein
          key: << checksum "project.clj" >>
      - store_artifacts:
          path: build
          destination: public
