version: 2
jobs:
  build:
    working_directory: /var/cleo-poc
    docker:
      - image: openjdk:8
    environment:
      LEIN_ROOT=nbd
    steps:
      - checkout
      - restore_cache:
          keys:
            - clj-1
            - cljs-2
      - run: bin/lein deps
      - run: bin/lein with-profile prod cljsbuild once ui
      - save_cache:
          paths:
            - ~/target
            - /root/.m2
            - ~/.lein
          key: cljs-2
      - save_cache:
          paths:
            - /root/.m2
            - $HOME/.lein
          key: << checksum "project.clj" >>

      - run: rm -rf build
      - run: bin/lein with-profile prod cljsbuild once ui
      - run: cp resources/public/index.html build
      - run: cp resources/public/icon.png build
      - run: echo "2222222222222222222222222222"
      - run: echo $AWS_ACCESS_KEY_ID

      - deploy:
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                apt-get update && apt-get install -y awscli
                aws s3 cp --recursive build s3://cleo-poc-bucket
              fi

      - store_artifacts:
          path: builid
