version: 2
jobs:
  build:
    working_directory: /var/cleo-poc
    docker:
      - image: openjdk:8
    environment:
      LEIN_ROOT=nbd
    steps:
      - checkout
      - restore_cache:
          keys:
            - clj-1
            - cljs-2
      - run: bin/lein deps
      - run: bin/lein with-profile prod cljsbuild once ui
      - save_cache:
          paths:
            - ~/target
            - /root/.m2
            - ~/.lein
          key: cljs-2
      - save_cache:
          paths:
            - /root/.m2
            - $HOME/.lein
          key: clj-1
      - store_artifacts:
          path: build
          destination: public
